# Generated by Django 4.1.3 on 2023-02-22 15:13

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('soft_essay', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Softessay_Essay_History',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('comment', models.CharField(blank=True, max_length=32, null=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('nickname', models.CharField(blank=True, max_length=32, null=True)),
                ('content', models.TextField(blank=True, null=True)),
                ('is_published', models.BooleanField(default=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('note', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'db_table': 'softessay_essay_history',
            },
        ),
        migrations.RemoveField(
            model_name='softessay_comment',
            name='body',
        ),
        migrations.RemoveField(
            model_name='softessay_comment',
            name='essay',
        ),
        migrations.RemoveField(
            model_name='softessay_comment',
            name='last_comment',
        ),
        migrations.RemoveConstraint(
            model_name='softessay_essay',
            name='unique essay by author',
        ),
        migrations.RemoveField(
            model_name='softessay_body',
            name='last_version',
        ),
        migrations.RemoveField(
            model_name='softessay_essay',
            name='forker',
        ),
        migrations.RemoveField(
            model_name='softessay_essay',
            name='version',
        ),
        migrations.AlterField(
            model_name='softessay_essay',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='softessay_essay',
            name='content',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='softessay_essay',
            constraint=models.UniqueConstraint(fields=('title', 'author'), name='unique essay by author'),
        ),
        migrations.DeleteModel(
            name='Softessay_Comment',
        ),
        migrations.AddField(
            model_name='softessay_essay_history',
            name='author',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='softessay_essay_history',
            name='essay',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='soft_essay.softessay_essay'),
        ),
        migrations.AddIndex(
            model_name='softessay_essay_history',
            index=models.Index(fields=['created_at'], name='softessay_e_created_d102e8_idx'),
        ),
        migrations.AddIndex(
            model_name='softessay_essay_history',
            index=models.Index(fields=['updated_at'], name='softessay_e_updated_b30ddd_idx'),
        ),
    ]
